sudo: false
language: python
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35-django22
    - python: "3.6"
      env: TOXENV=py36-django22
    - python: "3.7"
      env: TOXENV=py37-django22
    - python: "3.8"
      env: TOXENV=py38-django22
    - python: "pypy3"
      env: TOXENV=pypy3-django22

    - python: "3.6"
      env: TOXENV=py36-django30
    - python: "3.7"
      env: TOXENV=py37-django30
    - python: "3.8"
      env: TOXENV=py38-django30
    - python: "pypy3"
      env: TOXENV=pypy3-django30

    - python: "3.6"
      env: TOXENV=py36-django31
    - python: "3.7"
      env: TOXENV=py37-django31
    - python: "3.8"
      env: TOXENV=py38-django31
    - python: "pypy3"
      env: TOXENV=pypy3-django31
install: pip install tox-travis
script: tox # setting TOXENV is equivalent to calling `tox -e [ENV]`
notifications:
  email: false
