sudo: false
language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-django111
    - python: "3.4"
      env: TOXENV=py34-django111
    - python: "3.4"
      env: TOXENV=py35-django111
    - python: "3.5"
      env: TOXENV=py35-django21
    - python: "3.5"
      env: TOXENV=py35-django22
    - python: "3.6"
      env: TOXENV=py36-django111
    - python: "3.6"
      env: TOXENV=py36-django21
    - python: "3.6"
      env: TOXENV=py36-django22
    - python: "3.6"
      env: TOXENV=py36-djangomaster
    - python: "3.7"
      env: TOXENV=py37-django111
    - python: "3.7"
      env: TOXENV=py37-django21
    - python: "3.7"
      env: TOXENV=py37-django22
    - python: "3.7"
      env: TOXENV=py37-djangomaster
install: pip install tox-travis
script: tox # setting TOXENV is equivalent to calling `tox -e [ENV]`
notifications:
  email: false
